[default]
description = "Default permissions for the audio player plugin"
permissions = [
    "allow-play",
    "allow-pause",
    "allow-resume",
    "allow-stop",
    "allow-set-volume",
    "allow-seek",
    "allow-set-loop",
    "allow-get-state",
    "allow-get-position",
    "allow-get-duration",
    "allow-get-current-url",
]